### ISSUE TITLE
Alternative add-on

### ISSUE THREAD

**Issue by sergeevabc** [wsdfhjxc/crush-those-cookies#11]
Dear @wsdfhjxc, could you tell whether [Cookies Exterminator](https://addons.mozilla.org/en-US/firefox/addon/cookies-exterminator/) duplicates your add-on?

**Comment by wsdfhjxc** [comment]
Generally, it's an improved variant of this extension and more accurate alternative to SDC. It provides more control over removing cookies e.g. you can choose when to do it per site and it lets you remove individual cookies directly from toolbar menu. Also, taking care of existing SDC settings and importing whitelist is a nice feature too. There is no "strict domain checking" option though and it can be a little bit confusing at the very first time, without reading its description on AMO carefully. If you prefer more similarity to SDC, then you might want to install CE instead of CTC.

**Comment by sergeevabc** [comment]
Question-labeled issues are of little help when there are closed and moved to the attic. I suggest you creating FAQ section on main page and populate it with questions linked to your valuable answers.

**Comment by wsdfhjxc** [comment]
Yes, you are right, some extended information and explanations should be placed in README for those who still consider using this extension instead of the alternative one or just want to learn about it. I'll do it soon.
